// Code generated by protoc-gen-grpc-js-client
// source: version.proto
// DO NOT EDIT!

/*
This is a RSVP based Ajax client for gRPC gateway JSON APIs.
*/

var xhr = require('grpc-xhr');

function versionGet(p, conf) {
    path = '/api/apps/v1beta1/version'
    return xhr(path, 'GET', conf, p);
}

var services = {
    version: {
        get: versionGet
    }
};

module.exports = {appscode: {apps: {v1beta1: services}}};
